# Generated by Django 5.2.17 on 2026-09-13 16:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Geplant'), ('IN_PROGRESS', 'In Bearbeitung'), ('IMPLEMENTED', 'Umgesetzt'), ('OVERDUE', 'Überfällig / nicht umgesetzt')], default='PLANNED', max_length=24)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='risk',
            name='impact',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unbedeutend'), (2, 'Gering'), (3, 'Mittel'), (4, 'Hoch'), (5, 'Kritisch')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='risk',
            name='likelihood',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sehr unwahrscheinlich'), (2, 'Unwahrscheinlich'), (3, 'Möglich'), (4, 'Wahrscheinlich'), (5, 'Sehr wahrscheinlich')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='risk',
            name='treatment_strategy',
            field=models.CharField(blank=True, choices=[('AVOID', 'Vermeiden'), ('REDUCE', 'Reduzieren'), ('TRANSFER', 'Übertragen'), ('ACCEPT', 'Akzeptieren')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.CheckConstraint(condition=models.Q(('likelihood__gte', 1), ('likelihood__lte', 5)), name='risk_likelihood_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.CheckConstraint(condition=models.Q(('impact__gte', 1), ('impact__lte', 5)), name='risk_impact_1_to_5'),
        ),
        migrations.AddField(
            model_name='riskmeasure',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_measures', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='riskmeasure',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_measures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskmeasure',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='risks.risk'),
        ),
    ]
